import { JetBrains_Mono, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const jetMono = JetBrains_Mono({
  variable: "--font-jet",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const darkMode = true;
  return (
    <html lang="en" className={darkMode ? "dark" : ""}>
      <body
        className={`${geistSans.variable} ${jetMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
